1.2.1-alpha-7: Fix issue #1 (NoSuchMethodError on Java 8) - build.gradle specifies Java 8 as the target compatibility - Update README.md to warn users running Java 9+ - ApiRoutes.LoginCreateResult updated to prevent NoSuchMethodError if built on Java 9+ (temporary fix)